private:
    Testing: true
    SQLALCHEMY_DATABASE_URI: postgresql://simpledoge:testing@localhost:5432/simpledoge
    SECRET_KEY: 'sdfgljksdflg'
    BROKER_URL: ''
    CELERY_IMPORTS: ['simpledoge.tasks']
    CELERY_ACCEPT_CONTENT: ['pickle', 'json', 'msgpack', 'yaml']
    # the multiplier used on the last n shares to keep for counting share contributions
    last_n: 2
    fee: 1
    # min payout amount in satoshi, 500 full coins...
    #minimum_payout: 50000000000
    # 5 coins, for testnet testing
    minimum_payout: 500000000
    # the fee used when sending payouts to the coinserver
    payout_fee: 0.001
    rpc_signature: something_super_secret
    url: http://localhost:9400/
    coinserv:
        port: 19332
        address: 127.0.0.1
        username: litecoin
        password: testing
        wallet_pass: testing
        account: pool_address
    aliases:
        - name: Dogecoin Foundation General Fund
          address: DJ7zB7c5BsB9UJLy1rKQtY7c6CQfGiaRLM
          url: http://foundation.dogecoin.com/roadmap
        - name: The League Against AIDS
          url: http://www.leagueagainstaids.com/index2.html
          address: DRsyFLRwYpggbMNnkyTFYHW2uvLchqRmVD
        - name: Edwards Center
          url: http://www.leagueagainstaids.com/index2.html
          address: DRz7iTh5aYdr3MVjEXUA8Bfh1QerLq2m7u
        - name: Lucie's Place
          url: http://www.luciesplace.org/
          address: DNuakKH8cg5AjZzwfpnLWc1papDp3tUJ7q
        - name: Shiba Scout Rescue
          url: http://www.shibascoutrescue.com/
          address: D5MGiMCmxkpJkLBhKe9oN7h49X3t81e3kp

public:
    DEBUG: true
